### ISSUE TITLE
App stopped slicing and unable to save gcode to device or sd

### ISSUE THREAD

**Issue by jmarsee85** [p3d-dev/Print-To-3D#14]
So I have a monthly subscription and it has been working well for about a week. Just the other day it stopped slicing my STL files when I select slice it sits forever and it never slices, but if for some miraculous reason it does after 100 attempts and three hours of pulling my hair out, it doesn’t allow you to share or save the G code, to your device or your external SD card. At this point, I’m paying for a service that doesn’t work at all. Please help me I’ve tried everything.

**Comment by p3d-dev** [comment]
Sorry to hear, that you have trouble with the application. Is this one specific STL file, that it does not work or all of them ? 

Please start with a clean setup and check the basic slicing functionality. In order to do so, take these steps:
1. Create a default printer by long press the duplicate button in the sidebar for the printer. Please tap in the pop up menu the Default-menu entry.
2. Create a default process by long press the duplicate button in the sidebar for the process. Please tap in the pop up menu the Default-menu entry.

With these newly created profiles, please check, if slicing is working again.

**Comment by p3d-dev** [comment]
no further feedback received, so nothing else to do
