### ISSUE TITLE
Slicing stuck / does not complete

### ISSUE THREAD

**Issue by fluxor99232** [p3d-dev/Print-To-3D#15]
The cog animation stops spinning and the slicing never finishes, even with tiny and fairly simple objects. Sometimes it’s able to slice after removing one of multiple objects or disabling supports. But this makes the app unusable for me unfortunately. Back to Cura on my MacBook…

**Comment by p3d-dev** [comment]
Sorry to hear, that you have trouble with the application.  Which printer do you use ? Do you have modified any of the gcode configurations ?

Sometimes it is good to start with a clean setup and check the basic slicing functionality and take it from there. In order to do so, take these steps:

* Create a default printer by long press the duplicate button in the sidebar for the printer. Please tap in the pop up menu the Default-menu entry.
* Create a default process by long press the duplicate button in the sidebar for the process. Please tap in the pop up menu the Default-menu entry.
* With these newly created profiles, please check, if slicing is working as expected.

**Comment by fluxor99232** [comment]
Thank you for your reply! In this instance it was increasing the support part offset from 0.2 to 0.3 mm that allowed it it slice for whatever reason. Having helpful error messages would be great, if I could make a wish…
![IMG_5972](https://github.com/p3d-dev/Print-To-3D/assets/117677599/1da516ba-737e-439d-94ce-80607c15829e)
![IMG_5973](https://github.com/p3d-dev/Print-To-3D/assets/117677599/ae4c1f4c-d62a-41c9-94b4-57a03d6887ae)
