### ISSUE TITLE
Apps freezing using support 

### ISSUE THREAD

**Issue by kiwilambert** [p3d-dev/Print-To-3D#16]
![IMG_0508](https://github.com/p3d-dev/Print-To-3D/assets/147357205/ac32468b-9c61-4a38-91a7-24c75996fbee)
On Ender 3 pro, I’m not able to slice my STL when I used support. The application freezes.

**Comment by gin66** [comment]
Sorry for the inconvenience. Could you please share the STL-file for our analysis ?

**Comment by p3d-dev** [comment]
Sorry for the inconvenience. Could you please share the STL-file for our analysis ?

**Comment by kiwilambert** [comment]
There is the STL file.
[Chaise chien.zip](https://github.com/p3d-dev/Print-To-3D/files/12868849/Chaise.chien.zip)

**Comment by p3d-dev** [comment]
Thanks for sharing. The stl could be  successfully sliced on our side with and without support.
Could you please try to start with a new configuration (long press on the + button right from your default, then select Default) and only enable support as first step.

**Comment by kiwilambert** [comment]
I try and doesn’t work

**Comment by p3d-dev** [comment]
Sorry to hear that.

Could you please clarify, which iPad/iPhone do you use and which iOS version ?

**Comment by kiwilambert** [comment]
I have a iPad Air 4th generation with iPadOS 17.0.3

**Comment by p3d-dev** [comment]
Thanks for the information. This is getting puzzling. In order to check, we have reactivated our old 6th generation iPad Pro with iOS 16.2. And again, it slices out of the box without and with support.

Would you please try after each step and in that sequence
1. try again with a default printer ?
2. restart your iPad
3. Uninstall and reinstall PrintTo3D

Hope any of those steps lead to successful results.

**Comment by p3d-dev** [comment]
no further feedback received, so nothing else to do
