### ISSUE TITLE
Impossible to saving

### ISSUE THREAD

**Issue by Followmeintheshadow** [p3d-dev/Print-To-3D#17]
Hello, i can’t save the gcode on my micro sd.
The button télécharg/save si grey, not blue.
It’s very frustating.
I begin and it’s the 2nd day with this app.
The object is sliced.

i have a abonnment ´ i have pay,

why fix this problem ?

**Comment by p3d-dev** [comment]
Sorry for the inconvenience and encountering this problem after activating the subscription.

Based on your description, we have checked the source code and there are two conditions to keep this button in disabled state:
1. The slice view is not active
2. The internal job is still running

The other buttons (printer/filter/info) between the slice toggle button and the share button are disabled under the same condition. Could you please verify, if those buttons are too disabled ?

Which version of the application do you have installed ? You can find that info in the Quick Access Sidebar under the menu item "About". The latest version is PrintTo3D V3.26-3228. A similar phenomenon with the four buttons being disabled has been fixed in V3.8-2074.

In the meantime you could try the following - even so, it is not likely to fix this:
1. Restart your device
2. After slicing, rotate the device
3. After slicing, toggle the slice view twice, so that the view is back in the slicing view

Please provide feedback

**Comment by p3d-dev** [comment]
stale issue. So apparently solved
