### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by nallath** [p3d-dev/Print-To-3D#4]
So the repo is set to MIT, but it seems to have files that list it as having "CuraV2" as a source, which is licensed under LGPL and AGPL respectively. 

If this is what is used for the app presented here (https://apps.apple.com/ca/app/print-to-3d/id1614819811) I think you might need to release more source code than what you've done here. If you made any modifications to the CuraEngine (which as far as I understood it, also includes compiling it for IOS), you also need to make this public under AGPL.

**Comment by p3d-dev** [comment]
Thanks for the feedback. The "MIT" license is valid only for the files within the subdirectory tools, which we offer to the public for further usage. 

The json files are actually generated files from the build tool and have been added to the repository for convenience. Each of the json-files in the repository contain information about their applicable valid license.

Actually the application icon in the images subdirectory is too not MIT licensed, but property of our company.

We will update the README to clarify both aspects. Thanks for this input.

In case our application is installed on an iPhone/iPad accessible to you, please check the complete list of FOSS licenses under iOS Settings > PrintTo3D > Acknowledgements. There is none of GPL/AGPL/LGPL. Therefore code with one of these licenses is not used in our application. CuraEngine is licensed under LGPL-3.0 license and consequently the CuraEngine is not used.

**Comment by nallath** [comment]
CuraEngine is licensed under AGPL-3.0, not LGPL btw ;) 

So if you do run CuraEngine in the cloud somewhere it would still be required to release the source code for that.

**Comment by p3d-dev** [comment]
Thanks for the correction. We have mixed Cura and CuraEngine in regard to the license, while writing our answer here. Only Cura has switched five years ago to LGPL, while CuraEngine has stayed on AGPL.

Anyway, this does not matter, because CuraEngine is not in use. Neither inside the application nor using slicing in the cloud. Our application is not using any cloud service for slicing. The slicing is performed directly on iPad/iPhone. In case our application is installed on an iPhone/iPad accessible to you, please turn off WiFi and Bluetooth (+ cellular on iPhone). If you then use our app, slicing will continue to work as expected, which would be impossible for an app using cloud service for slicing.

**Comment by p3d-dev** [comment]
In case Ultimaker is interested in becoming the slicing engine of PrintTo3D, then Ultimaker would need to provide a solution for the license compatibility with AppStore guidelines. 

Our company is of the opinion, that there is no solution. Thereof Cura (or even parts of it) cannot be made available on iPad/iOS devices - as long as the AppStore guidelines stay as they are. And we assume, this holds true for Ultimaker, too.
