### ISSUE TITLE
cant select model

### ISSUE THREAD

**Issue by t3st-account** [p3d-dev/Print-To-3D#5]
When I have more than one model on the buildplate, I am unable to select certain Models. I am only able to select the first model that I added.

System: Ipad Pro 11” 2020 (2nd gen)

How to reproduce:
Put more than 1 model on the build plate -> Try to select second model -> Nothing happens…

Expected behaviour:
Model is selected manipulation menu(move rotate mirror…) opens

**Comment by p3d-dev** [comment]
Thanks for the feedback. The issue has been reproduced and root cause analysis started. The fixed SW version should be ready for release to Apple review today or latest tomorrow. Then it takes usually up to two days to be available in AppStore for SW update.

Please accept our apology for the inconvenience caused by this.

**Comment by p3d-dev** [comment]
The fixed application v3.9 has been pushed to Apple for review. Thanks for helping us to make PrintTo3D better and better.

**Comment by p3d-dev** [comment]
Could you please check, if it works for you now ?

**Comment by t3st-account** [comment]
yes, it works now.
Thanks for the fast fix :)
this issue can be closed now
